//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "HomePage.xaml.h"

void ::WarGames::HomePage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///HomePage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::WarGames::HomePage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->New = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->New))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WarGames::HomePage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HomePage::New_Click);
        }
        break;
    case 3:
        {
            this->Load = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Load))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WarGames::HomePage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HomePage::Load_Click);
        }
        break;
    case 4:
        {
            this->Stats = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Stats))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WarGames::HomePage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HomePage::Stats_Click);
        }
        break;
    case 5:
        {
            this->About = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->About))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WarGames::HomePage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&HomePage::About_Click);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::WarGames::HomePage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


