//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::WarGames::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::WarGames::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->nvTopLevelNav = safe_cast<::Windows::UI::Xaml::Controls::NavigationView^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::NavigationView^>(this->nvTopLevelNav))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WarGames::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::nvTopLevelNav_Loaded);
                (safe_cast<::Windows::UI::Xaml::Controls::NavigationView^>(this->nvTopLevelNav))->SelectionChanged += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::NavigationView^, ::Windows::UI::Xaml::Controls::NavigationViewSelectionChangedEventArgs^>(this, (void (::WarGames::MainPage::*)
                    (::Windows::UI::Xaml::Controls::NavigationView^, ::Windows::UI::Xaml::Controls::NavigationViewSelectionChangedEventArgs^))&MainPage::nvTopLevelNav_SelectionChanged);
                (safe_cast<::Windows::UI::Xaml::Controls::NavigationView^>(this->nvTopLevelNav))->ItemInvoked += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::NavigationView^, ::Windows::UI::Xaml::Controls::NavigationViewItemInvokedEventArgs^>(this, (void (::WarGames::MainPage::*)
                    (::Windows::UI::Xaml::Controls::NavigationView^, ::Windows::UI::Xaml::Controls::NavigationViewItemInvokedEventArgs^))&MainPage::nvTopLevelNav_ItemInvoked);
            }
            break;
        case 2:
            {
                this->contentFrame = safe_cast<::Windows::UI::Xaml::Controls::Frame^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::WarGames::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


