// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

void* winrt_make_WarGames_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::WarGames::factory_implementation::XamlMetaDataProvider>());
}
namespace winrt::WarGames
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<WarGames::implementation::XamlMetaDataProvider>())
    {
    }
}
