// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

#ifndef WINRT_Windows_Devices_Pwm_Provider_2_H
#define WINRT_Windows_Devices_Pwm_Provider_2_H
#include "winrt/impl/Windows.Devices.Pwm.Provider.1.h"
namespace winrt::Windows::Devices::Pwm::Provider
{
}
#endif
