// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

#ifndef WINRT_Windows_Devices_PointOfService_1_H
#define WINRT_Windows_Devices_PointOfService_1_H
#include "winrt/impl/Windows.Foundation.0.h"
#include "winrt/impl/Windows.Devices.PointOfService.0.h"
namespace winrt::Windows::Devices::PointOfService
{
    struct __declspec(empty_bases) IBarcodeScanner :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeScanner>
    {
        IBarcodeScanner(std::nullptr_t = nullptr) noexcept {}
        IBarcodeScanner(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IBarcodeScanner2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeScanner2>
    {
        IBarcodeScanner2(std::nullptr_t = nullptr) noexcept {}
        IBarcodeScanner2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IBarcodeScannerCapabilities :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeScannerCapabilities>
    {
        IBarcodeScannerCapabilities(std::nullptr_t = nullptr) noexcept {}
        IBarcodeScannerCapabilities(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IBarcodeScannerCapabilities1 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeScannerCapabilities1>
    {
        IBarcodeScannerCapabilities1(std::nullptr_t = nullptr) noexcept {}
        IBarcodeScannerCapabilities1(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IBarcodeScannerDataReceivedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeScannerDataReceivedEventArgs>
    {
        IBarcodeScannerDataReceivedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IBarcodeScannerDataReceivedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IBarcodeScannerErrorOccurredEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeScannerErrorOccurredEventArgs>
    {
        IBarcodeScannerErrorOccurredEventArgs(std::nullptr_t = nullptr) noexcept {}
        IBarcodeScannerErrorOccurredEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IBarcodeScannerImagePreviewReceivedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeScannerImagePreviewReceivedEventArgs>
    {
        IBarcodeScannerImagePreviewReceivedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IBarcodeScannerImagePreviewReceivedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IBarcodeScannerReport :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeScannerReport>
    {
        IBarcodeScannerReport(std::nullptr_t = nullptr) noexcept {}
        IBarcodeScannerReport(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IBarcodeScannerReportFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeScannerReportFactory>
    {
        IBarcodeScannerReportFactory(std::nullptr_t = nullptr) noexcept {}
        IBarcodeScannerReportFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IBarcodeScannerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeScannerStatics>
    {
        IBarcodeScannerStatics(std::nullptr_t = nullptr) noexcept {}
        IBarcodeScannerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IBarcodeScannerStatics2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeScannerStatics2>
    {
        IBarcodeScannerStatics2(std::nullptr_t = nullptr) noexcept {}
        IBarcodeScannerStatics2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IBarcodeScannerStatusUpdatedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeScannerStatusUpdatedEventArgs>
    {
        IBarcodeScannerStatusUpdatedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IBarcodeScannerStatusUpdatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IBarcodeSymbologiesStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeSymbologiesStatics>
    {
        IBarcodeSymbologiesStatics(std::nullptr_t = nullptr) noexcept {}
        IBarcodeSymbologiesStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IBarcodeSymbologiesStatics2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeSymbologiesStatics2>
    {
        IBarcodeSymbologiesStatics2(std::nullptr_t = nullptr) noexcept {}
        IBarcodeSymbologiesStatics2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IBarcodeSymbologyAttributes :
        Windows::Foundation::IInspectable,
        impl::consume_t<IBarcodeSymbologyAttributes>
    {
        IBarcodeSymbologyAttributes(std::nullptr_t = nullptr) noexcept {}
        IBarcodeSymbologyAttributes(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICashDrawer :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICashDrawer>
    {
        ICashDrawer(std::nullptr_t = nullptr) noexcept {}
        ICashDrawer(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICashDrawerCapabilities :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICashDrawerCapabilities>
    {
        ICashDrawerCapabilities(std::nullptr_t = nullptr) noexcept {}
        ICashDrawerCapabilities(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICashDrawerCloseAlarm :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICashDrawerCloseAlarm>
    {
        ICashDrawerCloseAlarm(std::nullptr_t = nullptr) noexcept {}
        ICashDrawerCloseAlarm(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICashDrawerEventSource :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICashDrawerEventSource>
    {
        ICashDrawerEventSource(std::nullptr_t = nullptr) noexcept {}
        ICashDrawerEventSource(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICashDrawerEventSourceEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICashDrawerEventSourceEventArgs>
    {
        ICashDrawerEventSourceEventArgs(std::nullptr_t = nullptr) noexcept {}
        ICashDrawerEventSourceEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICashDrawerStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICashDrawerStatics>
    {
        ICashDrawerStatics(std::nullptr_t = nullptr) noexcept {}
        ICashDrawerStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICashDrawerStatics2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICashDrawerStatics2>
    {
        ICashDrawerStatics2(std::nullptr_t = nullptr) noexcept {}
        ICashDrawerStatics2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICashDrawerStatus :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICashDrawerStatus>
    {
        ICashDrawerStatus(std::nullptr_t = nullptr) noexcept {}
        ICashDrawerStatus(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICashDrawerStatusUpdatedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICashDrawerStatusUpdatedEventArgs>
    {
        ICashDrawerStatusUpdatedEventArgs(std::nullptr_t = nullptr) noexcept {}
        ICashDrawerStatusUpdatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClaimedBarcodeScanner :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClaimedBarcodeScanner>,
        impl::require<Windows::Devices::PointOfService::IClaimedBarcodeScanner, Windows::Foundation::IClosable>
    {
        IClaimedBarcodeScanner(std::nullptr_t = nullptr) noexcept {}
        IClaimedBarcodeScanner(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClaimedBarcodeScanner1 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClaimedBarcodeScanner1>,
        impl::require<Windows::Devices::PointOfService::IClaimedBarcodeScanner1, Windows::Foundation::IClosable>
    {
        IClaimedBarcodeScanner1(std::nullptr_t = nullptr) noexcept {}
        IClaimedBarcodeScanner1(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClaimedBarcodeScanner2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClaimedBarcodeScanner2>,
        impl::require<Windows::Devices::PointOfService::IClaimedBarcodeScanner2, Windows::Foundation::IClosable>
    {
        IClaimedBarcodeScanner2(std::nullptr_t = nullptr) noexcept {}
        IClaimedBarcodeScanner2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClaimedBarcodeScanner3 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClaimedBarcodeScanner3>
    {
        IClaimedBarcodeScanner3(std::nullptr_t = nullptr) noexcept {}
        IClaimedBarcodeScanner3(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClaimedCashDrawer :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClaimedCashDrawer>,
        impl::require<Windows::Devices::PointOfService::IClaimedCashDrawer, Windows::Foundation::IClosable>
    {
        IClaimedCashDrawer(std::nullptr_t = nullptr) noexcept {}
        IClaimedCashDrawer(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClaimedJournalPrinter :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClaimedJournalPrinter>,
        impl::require<Windows::Devices::PointOfService::IClaimedJournalPrinter, Windows::Devices::PointOfService::ICommonClaimedPosPrinterStation>
    {
        IClaimedJournalPrinter(std::nullptr_t = nullptr) noexcept {}
        IClaimedJournalPrinter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClaimedLineDisplay :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClaimedLineDisplay>,
        impl::require<Windows::Devices::PointOfService::IClaimedLineDisplay, Windows::Foundation::IClosable>
    {
        IClaimedLineDisplay(std::nullptr_t = nullptr) noexcept {}
        IClaimedLineDisplay(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClaimedLineDisplay2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClaimedLineDisplay2>,
        impl::require<Windows::Devices::PointOfService::IClaimedLineDisplay2, Windows::Foundation::IClosable>
    {
        IClaimedLineDisplay2(std::nullptr_t = nullptr) noexcept {}
        IClaimedLineDisplay2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClaimedLineDisplayStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClaimedLineDisplayStatics>
    {
        IClaimedLineDisplayStatics(std::nullptr_t = nullptr) noexcept {}
        IClaimedLineDisplayStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClaimedMagneticStripeReader :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClaimedMagneticStripeReader>,
        impl::require<Windows::Devices::PointOfService::IClaimedMagneticStripeReader, Windows::Foundation::IClosable>
    {
        IClaimedMagneticStripeReader(std::nullptr_t = nullptr) noexcept {}
        IClaimedMagneticStripeReader(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClaimedPosPrinter :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClaimedPosPrinter>,
        impl::require<Windows::Devices::PointOfService::IClaimedPosPrinter, Windows::Foundation::IClosable>
    {
        IClaimedPosPrinter(std::nullptr_t = nullptr) noexcept {}
        IClaimedPosPrinter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClaimedReceiptPrinter :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClaimedReceiptPrinter>,
        impl::require<Windows::Devices::PointOfService::IClaimedReceiptPrinter, Windows::Devices::PointOfService::ICommonClaimedPosPrinterStation>
    {
        IClaimedReceiptPrinter(std::nullptr_t = nullptr) noexcept {}
        IClaimedReceiptPrinter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IClaimedSlipPrinter :
        Windows::Foundation::IInspectable,
        impl::consume_t<IClaimedSlipPrinter>,
        impl::require<Windows::Devices::PointOfService::IClaimedSlipPrinter, Windows::Devices::PointOfService::ICommonClaimedPosPrinterStation>
    {
        IClaimedSlipPrinter(std::nullptr_t = nullptr) noexcept {}
        IClaimedSlipPrinter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICommonClaimedPosPrinterStation :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICommonClaimedPosPrinterStation>
    {
        ICommonClaimedPosPrinterStation(std::nullptr_t = nullptr) noexcept {}
        ICommonClaimedPosPrinterStation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICommonPosPrintStationCapabilities :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICommonPosPrintStationCapabilities>
    {
        ICommonPosPrintStationCapabilities(std::nullptr_t = nullptr) noexcept {}
        ICommonPosPrintStationCapabilities(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ICommonReceiptSlipCapabilities :
        Windows::Foundation::IInspectable,
        impl::consume_t<ICommonReceiptSlipCapabilities>,
        impl::require<Windows::Devices::PointOfService::ICommonReceiptSlipCapabilities, Windows::Devices::PointOfService::ICommonPosPrintStationCapabilities>
    {
        ICommonReceiptSlipCapabilities(std::nullptr_t = nullptr) noexcept {}
        ICommonReceiptSlipCapabilities(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IJournalPrinterCapabilities :
        Windows::Foundation::IInspectable,
        impl::consume_t<IJournalPrinterCapabilities>,
        impl::require<Windows::Devices::PointOfService::IJournalPrinterCapabilities, Windows::Devices::PointOfService::ICommonPosPrintStationCapabilities>
    {
        IJournalPrinterCapabilities(std::nullptr_t = nullptr) noexcept {}
        IJournalPrinterCapabilities(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplay :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplay>,
        impl::require<Windows::Devices::PointOfService::ILineDisplay, Windows::Foundation::IClosable>
    {
        ILineDisplay(std::nullptr_t = nullptr) noexcept {}
        ILineDisplay(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplay2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplay2>,
        impl::require<Windows::Devices::PointOfService::ILineDisplay2, Windows::Foundation::IClosable>
    {
        ILineDisplay2(std::nullptr_t = nullptr) noexcept {}
        ILineDisplay2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplayAttributes :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplayAttributes>
    {
        ILineDisplayAttributes(std::nullptr_t = nullptr) noexcept {}
        ILineDisplayAttributes(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplayCapabilities :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplayCapabilities>
    {
        ILineDisplayCapabilities(std::nullptr_t = nullptr) noexcept {}
        ILineDisplayCapabilities(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplayCursor :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplayCursor>
    {
        ILineDisplayCursor(std::nullptr_t = nullptr) noexcept {}
        ILineDisplayCursor(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplayCursorAttributes :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplayCursorAttributes>
    {
        ILineDisplayCursorAttributes(std::nullptr_t = nullptr) noexcept {}
        ILineDisplayCursorAttributes(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplayCustomGlyphs :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplayCustomGlyphs>
    {
        ILineDisplayCustomGlyphs(std::nullptr_t = nullptr) noexcept {}
        ILineDisplayCustomGlyphs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplayMarquee :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplayMarquee>
    {
        ILineDisplayMarquee(std::nullptr_t = nullptr) noexcept {}
        ILineDisplayMarquee(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplayStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplayStatics>
    {
        ILineDisplayStatics(std::nullptr_t = nullptr) noexcept {}
        ILineDisplayStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplayStatics2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplayStatics2>
    {
        ILineDisplayStatics2(std::nullptr_t = nullptr) noexcept {}
        ILineDisplayStatics2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplayStatisticsCategorySelector :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplayStatisticsCategorySelector>
    {
        ILineDisplayStatisticsCategorySelector(std::nullptr_t = nullptr) noexcept {}
        ILineDisplayStatisticsCategorySelector(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplayStatusUpdatedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplayStatusUpdatedEventArgs>
    {
        ILineDisplayStatusUpdatedEventArgs(std::nullptr_t = nullptr) noexcept {}
        ILineDisplayStatusUpdatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplayStoredBitmap :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplayStoredBitmap>
    {
        ILineDisplayStoredBitmap(std::nullptr_t = nullptr) noexcept {}
        ILineDisplayStoredBitmap(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplayWindow :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplayWindow>,
        impl::require<Windows::Devices::PointOfService::ILineDisplayWindow, Windows::Foundation::IClosable>
    {
        ILineDisplayWindow(std::nullptr_t = nullptr) noexcept {}
        ILineDisplayWindow(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ILineDisplayWindow2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<ILineDisplayWindow2>,
        impl::require<Windows::Devices::PointOfService::ILineDisplayWindow2, Windows::Foundation::IClosable>
    {
        ILineDisplayWindow2(std::nullptr_t = nullptr) noexcept {}
        ILineDisplayWindow2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMagneticStripeReader :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMagneticStripeReader>
    {
        IMagneticStripeReader(std::nullptr_t = nullptr) noexcept {}
        IMagneticStripeReader(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMagneticStripeReaderAamvaCardDataReceivedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMagneticStripeReaderAamvaCardDataReceivedEventArgs>
    {
        IMagneticStripeReaderAamvaCardDataReceivedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMagneticStripeReaderAamvaCardDataReceivedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMagneticStripeReaderBankCardDataReceivedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMagneticStripeReaderBankCardDataReceivedEventArgs>
    {
        IMagneticStripeReaderBankCardDataReceivedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMagneticStripeReaderBankCardDataReceivedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMagneticStripeReaderCapabilities :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMagneticStripeReaderCapabilities>
    {
        IMagneticStripeReaderCapabilities(std::nullptr_t = nullptr) noexcept {}
        IMagneticStripeReaderCapabilities(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMagneticStripeReaderCardTypesStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMagneticStripeReaderCardTypesStatics>
    {
        IMagneticStripeReaderCardTypesStatics(std::nullptr_t = nullptr) noexcept {}
        IMagneticStripeReaderCardTypesStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMagneticStripeReaderEncryptionAlgorithmsStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMagneticStripeReaderEncryptionAlgorithmsStatics>
    {
        IMagneticStripeReaderEncryptionAlgorithmsStatics(std::nullptr_t = nullptr) noexcept {}
        IMagneticStripeReaderEncryptionAlgorithmsStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMagneticStripeReaderErrorOccurredEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMagneticStripeReaderErrorOccurredEventArgs>
    {
        IMagneticStripeReaderErrorOccurredEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMagneticStripeReaderErrorOccurredEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMagneticStripeReaderReport :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMagneticStripeReaderReport>
    {
        IMagneticStripeReaderReport(std::nullptr_t = nullptr) noexcept {}
        IMagneticStripeReaderReport(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMagneticStripeReaderStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMagneticStripeReaderStatics>
    {
        IMagneticStripeReaderStatics(std::nullptr_t = nullptr) noexcept {}
        IMagneticStripeReaderStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMagneticStripeReaderStatics2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMagneticStripeReaderStatics2>
    {
        IMagneticStripeReaderStatics2(std::nullptr_t = nullptr) noexcept {}
        IMagneticStripeReaderStatics2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMagneticStripeReaderStatusUpdatedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMagneticStripeReaderStatusUpdatedEventArgs>
    {
        IMagneticStripeReaderStatusUpdatedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMagneticStripeReaderStatusUpdatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMagneticStripeReaderTrackData :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMagneticStripeReaderTrackData>
    {
        IMagneticStripeReaderTrackData(std::nullptr_t = nullptr) noexcept {}
        IMagneticStripeReaderTrackData(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IMagneticStripeReaderVendorSpecificCardDataReceivedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMagneticStripeReaderVendorSpecificCardDataReceivedEventArgs>
    {
        IMagneticStripeReaderVendorSpecificCardDataReceivedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IMagneticStripeReaderVendorSpecificCardDataReceivedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPosPrinter :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPosPrinter>
    {
        IPosPrinter(std::nullptr_t = nullptr) noexcept {}
        IPosPrinter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPosPrinterCapabilities :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPosPrinterCapabilities>
    {
        IPosPrinterCapabilities(std::nullptr_t = nullptr) noexcept {}
        IPosPrinterCapabilities(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPosPrinterCharacterSetIdsStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPosPrinterCharacterSetIdsStatics>
    {
        IPosPrinterCharacterSetIdsStatics(std::nullptr_t = nullptr) noexcept {}
        IPosPrinterCharacterSetIdsStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPosPrinterJob :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPosPrinterJob>
    {
        IPosPrinterJob(std::nullptr_t = nullptr) noexcept {}
        IPosPrinterJob(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPosPrinterReleaseDeviceRequestedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPosPrinterReleaseDeviceRequestedEventArgs>
    {
        IPosPrinterReleaseDeviceRequestedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IPosPrinterReleaseDeviceRequestedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPosPrinterStatics :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPosPrinterStatics>
    {
        IPosPrinterStatics(std::nullptr_t = nullptr) noexcept {}
        IPosPrinterStatics(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPosPrinterStatics2 :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPosPrinterStatics2>
    {
        IPosPrinterStatics2(std::nullptr_t = nullptr) noexcept {}
        IPosPrinterStatics2(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPosPrinterStatus :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPosPrinterStatus>
    {
        IPosPrinterStatus(std::nullptr_t = nullptr) noexcept {}
        IPosPrinterStatus(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IPosPrinterStatusUpdatedEventArgs :
        Windows::Foundation::IInspectable,
        impl::consume_t<IPosPrinterStatusUpdatedEventArgs>
    {
        IPosPrinterStatusUpdatedEventArgs(std::nullptr_t = nullptr) noexcept {}
        IPosPrinterStatusUpdatedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IReceiptOrSlipJob :
        Windows::Foundation::IInspectable,
        impl::consume_t<IReceiptOrSlipJob>,
        impl::require<Windows::Devices::PointOfService::IReceiptOrSlipJob, Windows::Devices::PointOfService::IPosPrinterJob>
    {
        IReceiptOrSlipJob(std::nullptr_t = nullptr) noexcept {}
        IReceiptOrSlipJob(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IReceiptPrintJob :
        Windows::Foundation::IInspectable,
        impl::consume_t<IReceiptPrintJob>,
        impl::require<Windows::Devices::PointOfService::IReceiptPrintJob, Windows::Devices::PointOfService::IPosPrinterJob, Windows::Devices::PointOfService::IReceiptOrSlipJob>
    {
        IReceiptPrintJob(std::nullptr_t = nullptr) noexcept {}
        IReceiptPrintJob(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IReceiptPrinterCapabilities :
        Windows::Foundation::IInspectable,
        impl::consume_t<IReceiptPrinterCapabilities>,
        impl::require<Windows::Devices::PointOfService::IReceiptPrinterCapabilities, Windows::Devices::PointOfService::ICommonPosPrintStationCapabilities, Windows::Devices::PointOfService::ICommonReceiptSlipCapabilities>
    {
        IReceiptPrinterCapabilities(std::nullptr_t = nullptr) noexcept {}
        IReceiptPrinterCapabilities(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ISlipPrinterCapabilities :
        Windows::Foundation::IInspectable,
        impl::consume_t<ISlipPrinterCapabilities>,
        impl::require<Windows::Devices::PointOfService::ISlipPrinterCapabilities, Windows::Devices::PointOfService::ICommonPosPrintStationCapabilities, Windows::Devices::PointOfService::ICommonReceiptSlipCapabilities>
    {
        ISlipPrinterCapabilities(std::nullptr_t = nullptr) noexcept {}
        ISlipPrinterCapabilities(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUnifiedPosErrorData :
        Windows::Foundation::IInspectable,
        impl::consume_t<IUnifiedPosErrorData>
    {
        IUnifiedPosErrorData(std::nullptr_t = nullptr) noexcept {}
        IUnifiedPosErrorData(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IUnifiedPosErrorDataFactory :
        Windows::Foundation::IInspectable,
        impl::consume_t<IUnifiedPosErrorDataFactory>
    {
        IUnifiedPosErrorDataFactory(std::nullptr_t = nullptr) noexcept {}
        IUnifiedPosErrorDataFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
