// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

#ifndef WINRT_Windows_Graphics_DirectX_1_H
#define WINRT_Windows_Graphics_DirectX_1_H
#include "winrt/impl/Windows.Graphics.DirectX.0.h"
namespace winrt::Windows::Graphics::DirectX
{
}
#endif
