// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

#ifndef WINRT_Windows_UI_Composition_2_H
#define WINRT_Windows_UI_Composition_2_H
#include "winrt/impl/Windows.Foundation.1.h"
#include "winrt/impl/Windows.Foundation.Collections.1.h"
#include "winrt/impl/Windows.Graphics.1.h"
#include "winrt/impl/Windows.Graphics.Effects.1.h"
#include "winrt/impl/Windows.UI.Composition.1.h"
namespace winrt::Windows::UI::Composition
{
    struct __declspec(empty_bases) AmbientLight : Windows::UI::Composition::IAmbientLight,
        impl::base<AmbientLight, Windows::UI::Composition::CompositionLight, Windows::UI::Composition::CompositionObject>,
        impl::require<AmbientLight, Windows::UI::Composition::IAmbientLight2, Windows::UI::Composition::ICompositionLight, Windows::UI::Composition::ICompositionLight2, Windows::UI::Composition::ICompositionLight3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        AmbientLight(std::nullptr_t) noexcept {}
        AmbientLight(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IAmbientLight(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) AnimationController : Windows::UI::Composition::IAnimationController,
        impl::base<AnimationController, Windows::UI::Composition::CompositionObject>,
        impl::require<AnimationController, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        AnimationController(std::nullptr_t) noexcept {}
        AnimationController(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IAnimationController(ptr, take_ownership_from_abi) {}
        [[nodiscard]] static auto MaxPlaybackRate();
        [[nodiscard]] static auto MinPlaybackRate();
    };
    struct __declspec(empty_bases) BounceScalarNaturalMotionAnimation : Windows::UI::Composition::IBounceScalarNaturalMotionAnimation,
        impl::base<BounceScalarNaturalMotionAnimation, Windows::UI::Composition::ScalarNaturalMotionAnimation, Windows::UI::Composition::NaturalMotionAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<BounceScalarNaturalMotionAnimation, Windows::UI::Composition::IScalarNaturalMotionAnimation, Windows::UI::Composition::INaturalMotionAnimation, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        BounceScalarNaturalMotionAnimation(std::nullptr_t) noexcept {}
        BounceScalarNaturalMotionAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IBounceScalarNaturalMotionAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) BounceVector2NaturalMotionAnimation : Windows::UI::Composition::IBounceVector2NaturalMotionAnimation,
        impl::base<BounceVector2NaturalMotionAnimation, Windows::UI::Composition::Vector2NaturalMotionAnimation, Windows::UI::Composition::NaturalMotionAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<BounceVector2NaturalMotionAnimation, Windows::UI::Composition::IVector2NaturalMotionAnimation, Windows::UI::Composition::INaturalMotionAnimation, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        BounceVector2NaturalMotionAnimation(std::nullptr_t) noexcept {}
        BounceVector2NaturalMotionAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IBounceVector2NaturalMotionAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) BounceVector3NaturalMotionAnimation : Windows::UI::Composition::IBounceVector3NaturalMotionAnimation,
        impl::base<BounceVector3NaturalMotionAnimation, Windows::UI::Composition::Vector3NaturalMotionAnimation, Windows::UI::Composition::NaturalMotionAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<BounceVector3NaturalMotionAnimation, Windows::UI::Composition::IVector3NaturalMotionAnimation, Windows::UI::Composition::INaturalMotionAnimation, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        BounceVector3NaturalMotionAnimation(std::nullptr_t) noexcept {}
        BounceVector3NaturalMotionAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IBounceVector3NaturalMotionAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ColorKeyFrameAnimation : Windows::UI::Composition::IColorKeyFrameAnimation,
        impl::base<ColorKeyFrameAnimation, Windows::UI::Composition::KeyFrameAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<ColorKeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation2, Windows::UI::Composition::IKeyFrameAnimation3, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        ColorKeyFrameAnimation(std::nullptr_t) noexcept {}
        ColorKeyFrameAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IColorKeyFrameAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionAnimation : Windows::UI::Composition::ICompositionAnimation,
        impl::base<CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionAnimation(std::nullptr_t) noexcept {}
        CompositionAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionAnimationGroup : Windows::UI::Composition::ICompositionAnimationGroup,
        impl::base<CompositionAnimationGroup, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionAnimationGroup, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionAnimationGroup(std::nullptr_t) noexcept {}
        CompositionAnimationGroup(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionAnimationGroup(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionBackdropBrush : Windows::UI::Composition::ICompositionBackdropBrush,
        impl::base<CompositionBackdropBrush, Windows::UI::Composition::CompositionBrush, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionBackdropBrush, Windows::UI::Composition::ICompositionBrush, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionBackdropBrush(std::nullptr_t) noexcept {}
        CompositionBackdropBrush(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionBackdropBrush(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionBatchCompletedEventArgs : Windows::UI::Composition::ICompositionBatchCompletedEventArgs,
        impl::base<CompositionBatchCompletedEventArgs, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionBatchCompletedEventArgs, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionBatchCompletedEventArgs(std::nullptr_t) noexcept {}
        CompositionBatchCompletedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionBatchCompletedEventArgs(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionBrush : Windows::UI::Composition::ICompositionBrush,
        impl::base<CompositionBrush, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionBrush, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionBrush(std::nullptr_t) noexcept {}
        CompositionBrush(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionBrush(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionCapabilities : Windows::UI::Composition::ICompositionCapabilities
    {
        CompositionCapabilities(std::nullptr_t) noexcept {}
        CompositionCapabilities(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionCapabilities(ptr, take_ownership_from_abi) {}
        static auto GetForCurrentView();
    };
    struct __declspec(empty_bases) CompositionClip : Windows::UI::Composition::ICompositionClip,
        impl::base<CompositionClip, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionClip, Windows::UI::Composition::ICompositionClip2, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionClip(std::nullptr_t) noexcept {}
        CompositionClip(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionClip(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionColorBrush : Windows::UI::Composition::ICompositionColorBrush,
        impl::base<CompositionColorBrush, Windows::UI::Composition::CompositionBrush, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionColorBrush, Windows::UI::Composition::ICompositionBrush, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionColorBrush(std::nullptr_t) noexcept {}
        CompositionColorBrush(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionColorBrush(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionColorGradientStop : Windows::UI::Composition::ICompositionColorGradientStop,
        impl::base<CompositionColorGradientStop, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionColorGradientStop, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionColorGradientStop(std::nullptr_t) noexcept {}
        CompositionColorGradientStop(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionColorGradientStop(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionColorGradientStopCollection : Windows::UI::Composition::ICompositionColorGradientStopCollection
    {
        CompositionColorGradientStopCollection(std::nullptr_t) noexcept {}
        CompositionColorGradientStopCollection(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionColorGradientStopCollection(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionCommitBatch : Windows::UI::Composition::ICompositionCommitBatch,
        impl::base<CompositionCommitBatch, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionCommitBatch, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionCommitBatch(std::nullptr_t) noexcept {}
        CompositionCommitBatch(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionCommitBatch(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionContainerShape : Windows::UI::Composition::ICompositionContainerShape,
        impl::base<CompositionContainerShape, Windows::UI::Composition::CompositionShape, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionContainerShape, Windows::UI::Composition::ICompositionShape, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionContainerShape(std::nullptr_t) noexcept {}
        CompositionContainerShape(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionContainerShape(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionDrawingSurface : Windows::UI::Composition::ICompositionDrawingSurface,
        impl::base<CompositionDrawingSurface, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionDrawingSurface, Windows::UI::Composition::ICompositionSurface, Windows::UI::Composition::ICompositionDrawingSurface2, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionDrawingSurface(std::nullptr_t) noexcept {}
        CompositionDrawingSurface(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionDrawingSurface(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionEasingFunction : Windows::UI::Composition::ICompositionEasingFunction,
        impl::base<CompositionEasingFunction, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionEasingFunction, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionEasingFunction(std::nullptr_t) noexcept {}
        CompositionEasingFunction(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionEasingFunction(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionEffectBrush : Windows::UI::Composition::ICompositionEffectBrush,
        impl::base<CompositionEffectBrush, Windows::UI::Composition::CompositionBrush, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionEffectBrush, Windows::UI::Composition::ICompositionBrush, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionEffectBrush(std::nullptr_t) noexcept {}
        CompositionEffectBrush(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionEffectBrush(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionEffectFactory : Windows::UI::Composition::ICompositionEffectFactory,
        impl::base<CompositionEffectFactory, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionEffectFactory, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionEffectFactory(std::nullptr_t) noexcept {}
        CompositionEffectFactory(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionEffectFactory(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionEffectSourceParameter : Windows::UI::Composition::ICompositionEffectSourceParameter
    {
        CompositionEffectSourceParameter(std::nullptr_t) noexcept {}
        CompositionEffectSourceParameter(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionEffectSourceParameter(ptr, take_ownership_from_abi) {}
        CompositionEffectSourceParameter(param::hstring const& name);
    };
    struct __declspec(empty_bases) CompositionEllipseGeometry : Windows::UI::Composition::ICompositionEllipseGeometry,
        impl::base<CompositionEllipseGeometry, Windows::UI::Composition::CompositionGeometry, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionEllipseGeometry, Windows::UI::Composition::ICompositionGeometry, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionEllipseGeometry(std::nullptr_t) noexcept {}
        CompositionEllipseGeometry(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionEllipseGeometry(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionGeometry : Windows::UI::Composition::ICompositionGeometry,
        impl::base<CompositionGeometry, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionGeometry, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionGeometry(std::nullptr_t) noexcept {}
        CompositionGeometry(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionGeometry(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionGradientBrush : Windows::UI::Composition::ICompositionGradientBrush,
        impl::base<CompositionGradientBrush, Windows::UI::Composition::CompositionBrush, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionGradientBrush, Windows::UI::Composition::ICompositionBrush, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionGradientBrush(std::nullptr_t) noexcept {}
        CompositionGradientBrush(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionGradientBrush(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionGraphicsDevice : Windows::UI::Composition::ICompositionGraphicsDevice,
        impl::base<CompositionGraphicsDevice, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionGraphicsDevice, Windows::UI::Composition::ICompositionGraphicsDevice2, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionGraphicsDevice(std::nullptr_t) noexcept {}
        CompositionGraphicsDevice(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionGraphicsDevice(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionLight : Windows::UI::Composition::ICompositionLight,
        impl::base<CompositionLight, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionLight, Windows::UI::Composition::ICompositionLight2, Windows::UI::Composition::ICompositionLight3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionLight(std::nullptr_t) noexcept {}
        CompositionLight(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionLight(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionLineGeometry : Windows::UI::Composition::ICompositionLineGeometry,
        impl::base<CompositionLineGeometry, Windows::UI::Composition::CompositionGeometry, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionLineGeometry, Windows::UI::Composition::ICompositionGeometry, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionLineGeometry(std::nullptr_t) noexcept {}
        CompositionLineGeometry(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionLineGeometry(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionLinearGradientBrush : Windows::UI::Composition::ICompositionLinearGradientBrush,
        impl::base<CompositionLinearGradientBrush, Windows::UI::Composition::CompositionGradientBrush, Windows::UI::Composition::CompositionBrush, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionLinearGradientBrush, Windows::UI::Composition::ICompositionGradientBrush, Windows::UI::Composition::ICompositionBrush, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionLinearGradientBrush(std::nullptr_t) noexcept {}
        CompositionLinearGradientBrush(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionLinearGradientBrush(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionMaskBrush : Windows::UI::Composition::ICompositionMaskBrush,
        impl::base<CompositionMaskBrush, Windows::UI::Composition::CompositionBrush, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionMaskBrush, Windows::UI::Composition::ICompositionBrush, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionMaskBrush(std::nullptr_t) noexcept {}
        CompositionMaskBrush(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionMaskBrush(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionNineGridBrush : Windows::UI::Composition::ICompositionNineGridBrush,
        impl::base<CompositionNineGridBrush, Windows::UI::Composition::CompositionBrush, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionNineGridBrush, Windows::UI::Composition::ICompositionBrush, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionNineGridBrush(std::nullptr_t) noexcept {}
        CompositionNineGridBrush(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionNineGridBrush(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionObject : Windows::UI::Composition::ICompositionObject,
        impl::require<CompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionObject(std::nullptr_t) noexcept {}
        CompositionObject(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionObject(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionPath : Windows::UI::Composition::ICompositionPath,
        impl::require<CompositionPath, Windows::Graphics::IGeometrySource2D>
    {
        CompositionPath(std::nullptr_t) noexcept {}
        CompositionPath(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionPath(ptr, take_ownership_from_abi) {}
        CompositionPath(Windows::Graphics::IGeometrySource2D const& source);
    };
    struct __declspec(empty_bases) CompositionPathGeometry : Windows::UI::Composition::ICompositionPathGeometry,
        impl::base<CompositionPathGeometry, Windows::UI::Composition::CompositionGeometry, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionPathGeometry, Windows::UI::Composition::ICompositionGeometry, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionPathGeometry(std::nullptr_t) noexcept {}
        CompositionPathGeometry(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionPathGeometry(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionPropertySet : Windows::UI::Composition::ICompositionPropertySet,
        impl::base<CompositionPropertySet, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionPropertySet, Windows::UI::Composition::ICompositionPropertySet2, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionPropertySet(std::nullptr_t) noexcept {}
        CompositionPropertySet(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionPropertySet(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionRectangleGeometry : Windows::UI::Composition::ICompositionRectangleGeometry,
        impl::base<CompositionRectangleGeometry, Windows::UI::Composition::CompositionGeometry, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionRectangleGeometry, Windows::UI::Composition::ICompositionGeometry, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionRectangleGeometry(std::nullptr_t) noexcept {}
        CompositionRectangleGeometry(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionRectangleGeometry(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionRoundedRectangleGeometry : Windows::UI::Composition::ICompositionRoundedRectangleGeometry,
        impl::base<CompositionRoundedRectangleGeometry, Windows::UI::Composition::CompositionGeometry, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionRoundedRectangleGeometry, Windows::UI::Composition::ICompositionGeometry, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionRoundedRectangleGeometry(std::nullptr_t) noexcept {}
        CompositionRoundedRectangleGeometry(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionRoundedRectangleGeometry(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionScopedBatch : Windows::UI::Composition::ICompositionScopedBatch,
        impl::base<CompositionScopedBatch, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionScopedBatch, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionScopedBatch(std::nullptr_t) noexcept {}
        CompositionScopedBatch(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionScopedBatch(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionShadow : Windows::UI::Composition::ICompositionShadow,
        impl::base<CompositionShadow, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionShadow, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionShadow(std::nullptr_t) noexcept {}
        CompositionShadow(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionShadow(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionShape : Windows::UI::Composition::ICompositionShape,
        impl::base<CompositionShape, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionShape, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionShape(std::nullptr_t) noexcept {}
        CompositionShape(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionShape(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionShapeCollection : Windows::Foundation::Collections::IVector<Windows::UI::Composition::CompositionShape>,
        impl::base<CompositionShapeCollection, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionShapeCollection, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionShapeCollection(std::nullptr_t) noexcept {}
        CompositionShapeCollection(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::Collections::IVector<Windows::UI::Composition::CompositionShape>(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionSpriteShape : Windows::UI::Composition::ICompositionSpriteShape,
        impl::base<CompositionSpriteShape, Windows::UI::Composition::CompositionShape, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionSpriteShape, Windows::UI::Composition::ICompositionShape, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionSpriteShape(std::nullptr_t) noexcept {}
        CompositionSpriteShape(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionSpriteShape(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionStrokeDashArray : Windows::Foundation::Collections::IVector<float>,
        impl::base<CompositionStrokeDashArray, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionStrokeDashArray, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionStrokeDashArray(std::nullptr_t) noexcept {}
        CompositionStrokeDashArray(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::Collections::IVector<float>(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionSurfaceBrush : Windows::UI::Composition::ICompositionSurfaceBrush,
        impl::base<CompositionSurfaceBrush, Windows::UI::Composition::CompositionBrush, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionSurfaceBrush, Windows::UI::Composition::ICompositionSurfaceBrush2, Windows::UI::Composition::ICompositionBrush, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionSurfaceBrush(std::nullptr_t) noexcept {}
        CompositionSurfaceBrush(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionSurfaceBrush(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionTarget : Windows::UI::Composition::ICompositionTarget,
        impl::base<CompositionTarget, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionTarget, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionTarget(std::nullptr_t) noexcept {}
        CompositionTarget(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionTarget(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionViewBox : Windows::UI::Composition::ICompositionViewBox,
        impl::base<CompositionViewBox, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionViewBox, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionViewBox(std::nullptr_t) noexcept {}
        CompositionViewBox(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionViewBox(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CompositionVirtualDrawingSurface : Windows::UI::Composition::ICompositionVirtualDrawingSurface,
        impl::base<CompositionVirtualDrawingSurface, Windows::UI::Composition::CompositionDrawingSurface, Windows::UI::Composition::CompositionObject>,
        impl::require<CompositionVirtualDrawingSurface, Windows::UI::Composition::ICompositionDrawingSurface, Windows::UI::Composition::ICompositionSurface, Windows::UI::Composition::ICompositionDrawingSurface2, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CompositionVirtualDrawingSurface(std::nullptr_t) noexcept {}
        CompositionVirtualDrawingSurface(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositionVirtualDrawingSurface(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) Compositor : Windows::UI::Composition::ICompositor,
        impl::require<Compositor, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositor2, Windows::UI::Composition::ICompositor3, Windows::UI::Composition::ICompositor4, Windows::UI::Composition::ICompositor5>
    {
        Compositor(std::nullptr_t) noexcept {}
        Compositor(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICompositor(ptr, take_ownership_from_abi) {}
        Compositor();
        [[nodiscard]] static auto MaxGlobalPlaybackRate();
        [[nodiscard]] static auto MinGlobalPlaybackRate();
    };
    struct __declspec(empty_bases) ContainerVisual : Windows::UI::Composition::IContainerVisual,
        impl::base<ContainerVisual, Windows::UI::Composition::Visual, Windows::UI::Composition::CompositionObject>,
        impl::require<ContainerVisual, Windows::UI::Composition::IVisual, Windows::UI::Composition::IVisual2, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        ContainerVisual(std::nullptr_t) noexcept {}
        ContainerVisual(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IContainerVisual(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) CubicBezierEasingFunction : Windows::UI::Composition::ICubicBezierEasingFunction,
        impl::base<CubicBezierEasingFunction, Windows::UI::Composition::CompositionEasingFunction, Windows::UI::Composition::CompositionObject>,
        impl::require<CubicBezierEasingFunction, Windows::UI::Composition::ICompositionEasingFunction, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        CubicBezierEasingFunction(std::nullptr_t) noexcept {}
        CubicBezierEasingFunction(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ICubicBezierEasingFunction(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) DistantLight : Windows::UI::Composition::IDistantLight,
        impl::base<DistantLight, Windows::UI::Composition::CompositionLight, Windows::UI::Composition::CompositionObject>,
        impl::require<DistantLight, Windows::UI::Composition::IDistantLight2, Windows::UI::Composition::ICompositionLight, Windows::UI::Composition::ICompositionLight2, Windows::UI::Composition::ICompositionLight3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        DistantLight(std::nullptr_t) noexcept {}
        DistantLight(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IDistantLight(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) DropShadow : Windows::UI::Composition::IDropShadow,
        impl::base<DropShadow, Windows::UI::Composition::CompositionShadow, Windows::UI::Composition::CompositionObject>,
        impl::require<DropShadow, Windows::UI::Composition::IDropShadow2, Windows::UI::Composition::ICompositionShadow, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        DropShadow(std::nullptr_t) noexcept {}
        DropShadow(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IDropShadow(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ExpressionAnimation : Windows::UI::Composition::IExpressionAnimation,
        impl::base<ExpressionAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<ExpressionAnimation, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        ExpressionAnimation(std::nullptr_t) noexcept {}
        ExpressionAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IExpressionAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ImplicitAnimationCollection : Windows::UI::Composition::IImplicitAnimationCollection,
        impl::base<ImplicitAnimationCollection, Windows::UI::Composition::CompositionObject>,
        impl::require<ImplicitAnimationCollection, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        ImplicitAnimationCollection(std::nullptr_t) noexcept {}
        ImplicitAnimationCollection(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IImplicitAnimationCollection(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) InitialValueExpressionCollection : Windows::Foundation::Collections::IMap<hstring, hstring>,
        impl::base<InitialValueExpressionCollection, Windows::UI::Composition::CompositionObject>,
        impl::require<InitialValueExpressionCollection, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        InitialValueExpressionCollection(std::nullptr_t) noexcept {}
        InitialValueExpressionCollection(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::Collections::IMap<hstring, hstring>(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) InsetClip : Windows::UI::Composition::IInsetClip,
        impl::base<InsetClip, Windows::UI::Composition::CompositionClip, Windows::UI::Composition::CompositionObject>,
        impl::require<InsetClip, Windows::UI::Composition::ICompositionClip, Windows::UI::Composition::ICompositionClip2, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        InsetClip(std::nullptr_t) noexcept {}
        InsetClip(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IInsetClip(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) KeyFrameAnimation : Windows::UI::Composition::IKeyFrameAnimation,
        impl::base<KeyFrameAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<KeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation2, Windows::UI::Composition::IKeyFrameAnimation3, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        KeyFrameAnimation(std::nullptr_t) noexcept {}
        KeyFrameAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IKeyFrameAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) LayerVisual : Windows::UI::Composition::ILayerVisual,
        impl::base<LayerVisual, Windows::UI::Composition::ContainerVisual, Windows::UI::Composition::Visual, Windows::UI::Composition::CompositionObject>,
        impl::require<LayerVisual, Windows::UI::Composition::ILayerVisual2, Windows::UI::Composition::IContainerVisual, Windows::UI::Composition::IVisual, Windows::UI::Composition::IVisual2, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        LayerVisual(std::nullptr_t) noexcept {}
        LayerVisual(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ILayerVisual(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) LinearEasingFunction : Windows::UI::Composition::ILinearEasingFunction,
        impl::base<LinearEasingFunction, Windows::UI::Composition::CompositionEasingFunction, Windows::UI::Composition::CompositionObject>,
        impl::require<LinearEasingFunction, Windows::UI::Composition::ICompositionEasingFunction, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        LinearEasingFunction(std::nullptr_t) noexcept {}
        LinearEasingFunction(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ILinearEasingFunction(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) NaturalMotionAnimation : Windows::UI::Composition::INaturalMotionAnimation,
        impl::base<NaturalMotionAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<NaturalMotionAnimation, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        NaturalMotionAnimation(std::nullptr_t) noexcept {}
        NaturalMotionAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::INaturalMotionAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) PathKeyFrameAnimation : Windows::UI::Composition::IPathKeyFrameAnimation,
        impl::base<PathKeyFrameAnimation, Windows::UI::Composition::KeyFrameAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<PathKeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation2, Windows::UI::Composition::IKeyFrameAnimation3, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        PathKeyFrameAnimation(std::nullptr_t) noexcept {}
        PathKeyFrameAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IPathKeyFrameAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) PointLight : Windows::UI::Composition::IPointLight,
        impl::base<PointLight, Windows::UI::Composition::CompositionLight, Windows::UI::Composition::CompositionObject>,
        impl::require<PointLight, Windows::UI::Composition::IPointLight2, Windows::UI::Composition::IPointLight3, Windows::UI::Composition::ICompositionLight, Windows::UI::Composition::ICompositionLight2, Windows::UI::Composition::ICompositionLight3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        PointLight(std::nullptr_t) noexcept {}
        PointLight(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IPointLight(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) QuaternionKeyFrameAnimation : Windows::UI::Composition::IQuaternionKeyFrameAnimation,
        impl::base<QuaternionKeyFrameAnimation, Windows::UI::Composition::KeyFrameAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<QuaternionKeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation2, Windows::UI::Composition::IKeyFrameAnimation3, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        QuaternionKeyFrameAnimation(std::nullptr_t) noexcept {}
        QuaternionKeyFrameAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IQuaternionKeyFrameAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) RenderingDeviceReplacedEventArgs : Windows::UI::Composition::IRenderingDeviceReplacedEventArgs,
        impl::base<RenderingDeviceReplacedEventArgs, Windows::UI::Composition::CompositionObject>,
        impl::require<RenderingDeviceReplacedEventArgs, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        RenderingDeviceReplacedEventArgs(std::nullptr_t) noexcept {}
        RenderingDeviceReplacedEventArgs(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IRenderingDeviceReplacedEventArgs(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ScalarKeyFrameAnimation : Windows::UI::Composition::IScalarKeyFrameAnimation,
        impl::base<ScalarKeyFrameAnimation, Windows::UI::Composition::KeyFrameAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<ScalarKeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation2, Windows::UI::Composition::IKeyFrameAnimation3, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        ScalarKeyFrameAnimation(std::nullptr_t) noexcept {}
        ScalarKeyFrameAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IScalarKeyFrameAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ScalarNaturalMotionAnimation : Windows::UI::Composition::IScalarNaturalMotionAnimation,
        impl::base<ScalarNaturalMotionAnimation, Windows::UI::Composition::NaturalMotionAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<ScalarNaturalMotionAnimation, Windows::UI::Composition::INaturalMotionAnimation, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        ScalarNaturalMotionAnimation(std::nullptr_t) noexcept {}
        ScalarNaturalMotionAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IScalarNaturalMotionAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) ShapeVisual : Windows::UI::Composition::IShapeVisual,
        impl::base<ShapeVisual, Windows::UI::Composition::ContainerVisual, Windows::UI::Composition::Visual, Windows::UI::Composition::CompositionObject>,
        impl::require<ShapeVisual, Windows::UI::Composition::IContainerVisual, Windows::UI::Composition::IVisual, Windows::UI::Composition::IVisual2, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        ShapeVisual(std::nullptr_t) noexcept {}
        ShapeVisual(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IShapeVisual(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) SpotLight : Windows::UI::Composition::ISpotLight,
        impl::base<SpotLight, Windows::UI::Composition::CompositionLight, Windows::UI::Composition::CompositionObject>,
        impl::require<SpotLight, Windows::UI::Composition::ISpotLight2, Windows::UI::Composition::ISpotLight3, Windows::UI::Composition::ICompositionLight, Windows::UI::Composition::ICompositionLight2, Windows::UI::Composition::ICompositionLight3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        SpotLight(std::nullptr_t) noexcept {}
        SpotLight(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ISpotLight(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) SpringScalarNaturalMotionAnimation : Windows::UI::Composition::ISpringScalarNaturalMotionAnimation,
        impl::base<SpringScalarNaturalMotionAnimation, Windows::UI::Composition::ScalarNaturalMotionAnimation, Windows::UI::Composition::NaturalMotionAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<SpringScalarNaturalMotionAnimation, Windows::UI::Composition::IScalarNaturalMotionAnimation, Windows::UI::Composition::INaturalMotionAnimation, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        SpringScalarNaturalMotionAnimation(std::nullptr_t) noexcept {}
        SpringScalarNaturalMotionAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ISpringScalarNaturalMotionAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) SpringVector2NaturalMotionAnimation : Windows::UI::Composition::ISpringVector2NaturalMotionAnimation,
        impl::base<SpringVector2NaturalMotionAnimation, Windows::UI::Composition::Vector2NaturalMotionAnimation, Windows::UI::Composition::NaturalMotionAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<SpringVector2NaturalMotionAnimation, Windows::UI::Composition::IVector2NaturalMotionAnimation, Windows::UI::Composition::INaturalMotionAnimation, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        SpringVector2NaturalMotionAnimation(std::nullptr_t) noexcept {}
        SpringVector2NaturalMotionAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ISpringVector2NaturalMotionAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) SpringVector3NaturalMotionAnimation : Windows::UI::Composition::ISpringVector3NaturalMotionAnimation,
        impl::base<SpringVector3NaturalMotionAnimation, Windows::UI::Composition::Vector3NaturalMotionAnimation, Windows::UI::Composition::NaturalMotionAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<SpringVector3NaturalMotionAnimation, Windows::UI::Composition::IVector3NaturalMotionAnimation, Windows::UI::Composition::INaturalMotionAnimation, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        SpringVector3NaturalMotionAnimation(std::nullptr_t) noexcept {}
        SpringVector3NaturalMotionAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ISpringVector3NaturalMotionAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) SpriteVisual : Windows::UI::Composition::ISpriteVisual,
        impl::base<SpriteVisual, Windows::UI::Composition::ContainerVisual, Windows::UI::Composition::Visual, Windows::UI::Composition::CompositionObject>,
        impl::require<SpriteVisual, Windows::UI::Composition::ISpriteVisual2, Windows::UI::Composition::IContainerVisual, Windows::UI::Composition::IVisual, Windows::UI::Composition::IVisual2, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        SpriteVisual(std::nullptr_t) noexcept {}
        SpriteVisual(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::ISpriteVisual(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) StepEasingFunction : Windows::UI::Composition::IStepEasingFunction,
        impl::base<StepEasingFunction, Windows::UI::Composition::CompositionEasingFunction, Windows::UI::Composition::CompositionObject>,
        impl::require<StepEasingFunction, Windows::UI::Composition::ICompositionEasingFunction, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        StepEasingFunction(std::nullptr_t) noexcept {}
        StepEasingFunction(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IStepEasingFunction(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) Vector2KeyFrameAnimation : Windows::UI::Composition::IVector2KeyFrameAnimation,
        impl::base<Vector2KeyFrameAnimation, Windows::UI::Composition::KeyFrameAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<Vector2KeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation2, Windows::UI::Composition::IKeyFrameAnimation3, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        Vector2KeyFrameAnimation(std::nullptr_t) noexcept {}
        Vector2KeyFrameAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IVector2KeyFrameAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) Vector2NaturalMotionAnimation : Windows::UI::Composition::IVector2NaturalMotionAnimation,
        impl::base<Vector2NaturalMotionAnimation, Windows::UI::Composition::NaturalMotionAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<Vector2NaturalMotionAnimation, Windows::UI::Composition::INaturalMotionAnimation, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        Vector2NaturalMotionAnimation(std::nullptr_t) noexcept {}
        Vector2NaturalMotionAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IVector2NaturalMotionAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) Vector3KeyFrameAnimation : Windows::UI::Composition::IVector3KeyFrameAnimation,
        impl::base<Vector3KeyFrameAnimation, Windows::UI::Composition::KeyFrameAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<Vector3KeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation2, Windows::UI::Composition::IKeyFrameAnimation3, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        Vector3KeyFrameAnimation(std::nullptr_t) noexcept {}
        Vector3KeyFrameAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IVector3KeyFrameAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) Vector3NaturalMotionAnimation : Windows::UI::Composition::IVector3NaturalMotionAnimation,
        impl::base<Vector3NaturalMotionAnimation, Windows::UI::Composition::NaturalMotionAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<Vector3NaturalMotionAnimation, Windows::UI::Composition::INaturalMotionAnimation, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        Vector3NaturalMotionAnimation(std::nullptr_t) noexcept {}
        Vector3NaturalMotionAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IVector3NaturalMotionAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) Vector4KeyFrameAnimation : Windows::UI::Composition::IVector4KeyFrameAnimation,
        impl::base<Vector4KeyFrameAnimation, Windows::UI::Composition::KeyFrameAnimation, Windows::UI::Composition::CompositionAnimation, Windows::UI::Composition::CompositionObject>,
        impl::require<Vector4KeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation, Windows::UI::Composition::IKeyFrameAnimation2, Windows::UI::Composition::IKeyFrameAnimation3, Windows::UI::Composition::ICompositionAnimation, Windows::UI::Composition::ICompositionAnimation2, Windows::UI::Composition::ICompositionAnimationBase, Windows::UI::Composition::ICompositionAnimation3, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        Vector4KeyFrameAnimation(std::nullptr_t) noexcept {}
        Vector4KeyFrameAnimation(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IVector4KeyFrameAnimation(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) Visual : Windows::UI::Composition::IVisual,
        impl::base<Visual, Windows::UI::Composition::CompositionObject>,
        impl::require<Visual, Windows::UI::Composition::IVisual2, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        Visual(std::nullptr_t) noexcept {}
        Visual(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IVisual(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) VisualCollection : Windows::UI::Composition::IVisualCollection,
        impl::base<VisualCollection, Windows::UI::Composition::CompositionObject>,
        impl::require<VisualCollection, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        VisualCollection(std::nullptr_t) noexcept {}
        VisualCollection(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IVisualCollection(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) VisualUnorderedCollection : Windows::UI::Composition::IVisualUnorderedCollection,
        impl::base<VisualUnorderedCollection, Windows::UI::Composition::CompositionObject>,
        impl::require<VisualUnorderedCollection, Windows::UI::Composition::ICompositionObject, Windows::Foundation::IClosable, Windows::UI::Composition::ICompositionObject2, Windows::UI::Composition::ICompositionObject3, Windows::UI::Composition::ICompositionObject4>
    {
        VisualUnorderedCollection(std::nullptr_t) noexcept {}
        VisualUnorderedCollection(void* ptr, take_ownership_from_abi_t) noexcept : Windows::UI::Composition::IVisualUnorderedCollection(ptr, take_ownership_from_abi) {}
    };
}
#endif
