// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

#ifndef WINRT_Windows_Perception_People_2_H
#define WINRT_Windows_Perception_People_2_H
#include "winrt/impl/Windows.Perception.People.1.h"
namespace winrt::Windows::Perception::People
{
    struct __declspec(empty_bases) HeadPose : Windows::Perception::People::IHeadPose
    {
        HeadPose(std::nullptr_t) noexcept {}
        HeadPose(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Perception::People::IHeadPose(ptr, take_ownership_from_abi) {}
    };
}
#endif
