// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

#ifndef WINRT_Windows_Perception_People_1_H
#define WINRT_Windows_Perception_People_1_H
#include "winrt/impl/Windows.Perception.People.0.h"
namespace winrt::Windows::Perception::People
{
    struct __declspec(empty_bases) IHeadPose :
        Windows::Foundation::IInspectable,
        impl::consume_t<IHeadPose>
    {
        IHeadPose(std::nullptr_t = nullptr) noexcept {}
        IHeadPose(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
