// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

#ifndef WINRT_Windows_Phone_ApplicationModel_2_H
#define WINRT_Windows_Phone_ApplicationModel_2_H
#include "winrt/impl/Windows.Phone.ApplicationModel.1.h"
namespace winrt::Windows::Phone::ApplicationModel
{
    struct ApplicationProfile
    {
        ApplicationProfile() = delete;
        [[nodiscard]] static auto Modes();
    };
}
#endif
