// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

#ifndef WINRT_Windows_Media_Render_1_H
#define WINRT_Windows_Media_Render_1_H
#include "winrt/impl/Windows.Media.Render.0.h"
namespace winrt::Windows::Media::Render
{
}
#endif
