// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

#ifndef WINRT_Windows_Phone_Speech_Recognition_0_H
#define WINRT_Windows_Phone_Speech_Recognition_0_H
namespace winrt::Windows::Phone::Speech::Recognition
{
    enum class SpeechRecognitionUIStatus : int32_t
    {
        Succeeded = 0,
        Busy = 1,
        Cancelled = 2,
        Preempted = 3,
        PrivacyPolicyDeclined = 4,
    };
}
namespace winrt::impl
{
    template <> struct category<Windows::Phone::Speech::Recognition::SpeechRecognitionUIStatus>
    {
        using type = enum_category;
    };
    template <> struct name<Windows::Phone::Speech::Recognition::SpeechRecognitionUIStatus>
    {
        static constexpr auto & value{ L"Windows.Phone.Speech.Recognition.SpeechRecognitionUIStatus" };
    };
}
#endif
