// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

#ifndef WINRT_WarGames_1_H
#define WINRT_WarGames_1_H
#include "winrt/impl/WarGames.0.h"
namespace winrt::WarGames
{
    struct __declspec(empty_bases) IMainPage :
        Windows::Foundation::IInspectable,
        impl::consume_t<IMainPage>
    {
        IMainPage(std::nullptr_t = nullptr) noexcept {}
        IMainPage(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
