// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

#ifndef WINRT_Windows_Phone_System_Power_0_H
#define WINRT_Windows_Phone_System_Power_0_H
namespace winrt::Windows::Foundation
{
    template <typename T> struct EventHandler;
    struct EventRegistrationToken;
}
namespace winrt::Windows::Phone::System::Power
{
    enum class PowerSavingMode : int32_t
    {
        Off = 0,
        On = 1,
    };
    struct IPowerManagerStatics;
    struct IPowerManagerStatics2;
    struct PowerManager;
}
namespace winrt::impl
{
    template <> struct category<Windows::Phone::System::Power::IPowerManagerStatics>
    {
        using type = interface_category;
    };
    template <> struct category<Windows::Phone::System::Power::IPowerManagerStatics2>
    {
        using type = interface_category;
    };
    template <> struct category<Windows::Phone::System::Power::PowerManager>
    {
        using type = class_category;
    };
    template <> struct category<Windows::Phone::System::Power::PowerSavingMode>
    {
        using type = enum_category;
    };
    template <> struct name<Windows::Phone::System::Power::IPowerManagerStatics>
    {
        static constexpr auto & value{ L"Windows.Phone.System.Power.IPowerManagerStatics" };
    };
    template <> struct name<Windows::Phone::System::Power::IPowerManagerStatics2>
    {
        static constexpr auto & value{ L"Windows.Phone.System.Power.IPowerManagerStatics2" };
    };
    template <> struct name<Windows::Phone::System::Power::PowerManager>
    {
        static constexpr auto & value{ L"Windows.Phone.System.Power.PowerManager" };
    };
    template <> struct name<Windows::Phone::System::Power::PowerSavingMode>
    {
        static constexpr auto & value{ L"Windows.Phone.System.Power.PowerSavingMode" };
    };
    template <> struct guid_storage<Windows::Phone::System::Power::IPowerManagerStatics>
    {
        static constexpr guid value{ 0x25DE8FD0,0x1C5B,0x11E1,{ 0xBD,0xDB,0x08,0x00,0x20,0x0C,0x9A,0x66 } };
    };
    template <> struct guid_storage<Windows::Phone::System::Power::IPowerManagerStatics2>
    {
        static constexpr guid value{ 0x596236CF,0x1918,0x4551,{ 0xA4,0x66,0xC5,0x1A,0xAE,0x37,0x3B,0xF8 } };
    };
    template <> struct abi<Windows::Phone::System::Power::IPowerManagerStatics>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_PowerSavingMode(int32_t*) noexcept = 0;
            virtual int32_t __stdcall add_PowerSavingModeChanged(void*, winrt::event_token*) noexcept = 0;
            virtual int32_t __stdcall remove_PowerSavingModeChanged(winrt::event_token) noexcept = 0;
        };
    };
    template <> struct abi<Windows::Phone::System::Power::IPowerManagerStatics2>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_PowerSavingModeEnabled(bool*) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_Windows_Phone_System_Power_IPowerManagerStatics
    {
        [[nodiscard]] auto PowerSavingMode() const;
        auto PowerSavingModeChanged(Windows::Foundation::EventHandler<Windows::Foundation::IInspectable> const& changeHandler) const;
        using PowerSavingModeChanged_revoker = impl::event_revoker<Windows::Phone::System::Power::IPowerManagerStatics, &impl::abi_t<Windows::Phone::System::Power::IPowerManagerStatics>::remove_PowerSavingModeChanged>;
        [[nodiscard]] PowerSavingModeChanged_revoker PowerSavingModeChanged(auto_revoke_t, Windows::Foundation::EventHandler<Windows::Foundation::IInspectable> const& changeHandler) const;
        auto PowerSavingModeChanged(winrt::event_token const& token) const noexcept;
    };
    template <> struct consume<Windows::Phone::System::Power::IPowerManagerStatics>
    {
        template <typename D> using type = consume_Windows_Phone_System_Power_IPowerManagerStatics<D>;
    };
    template <typename D>
    struct consume_Windows_Phone_System_Power_IPowerManagerStatics2
    {
        [[nodiscard]] auto PowerSavingModeEnabled() const;
    };
    template <> struct consume<Windows::Phone::System::Power::IPowerManagerStatics2>
    {
        template <typename D> using type = consume_Windows_Phone_System_Power_IPowerManagerStatics2<D>;
    };
}
#endif
