// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190730.2

#ifndef WINRT_Windows_Phone_Speech_Recognition_H
#define WINRT_Windows_Phone_Speech_Recognition_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.190730.2"), "Mismatched C++/WinRT headers.");
#include "winrt/impl/Windows.Phone.Speech.Recognition.2.h"
namespace winrt::impl
{
}
namespace winrt::Windows::Phone::Speech::Recognition
{
}
namespace std
{
}
#endif
